name: Deploy medpullwebsite to S3/CloudFront

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'medpullwebsite/**'
      - '.github/workflows/deploy-medpullwebsite.yml'

permissions:
  id-token: write
  contents: read

env:
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload assets with long cache
        run: |
          aws s3 sync medpullwebsite s3://$S3_BUCKET \
            --delete \
            --exclude "*.html" \
            --cache-control "public, max-age=31536000, immutable"

      - name: Upload HTML with no-cache
        run: |
          aws s3 cp medpullwebsite s3://$S3_BUCKET --recursive \
            --exclude "*" --include "*.html" \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html; charset=utf-8" \
            --metadata-directive REPLACE

      - name: Invalidate CloudFront
        if: env.CLOUDFRONT_DISTRIBUTION_ID != ''
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"
